version: '2'

services:

  app:
    build: .
    container_name: bono_parcial_app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://98.82.9.114:3306/properties?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
